services:
    - name           : hailataxii.com
      username       : guest
      password       : guest
      discovery_url  : http://hailataxii.com/taxii-discovery-service
      client_type     : edge
      feeds          :
        - system.Default


neo4j_username: neo4j
neo4j_password: neo4j
neo4j_host: 192.168.99.100
neo4j_port: 7474
